// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:9ca13ab0-3d28-4dda-8aa4-88bb8cf7ba4d',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '5555eb2cd7d7476abacd08c09192dc3f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '2ec4713b-7f1b-4617-a2e9-7f35844a983c',
    'aws_project_name': 'Alfred',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'alfred-mobilehub-1760917209',
}

export default awsmobile;
